# Generated by Django 3.1.1 on 2020-09-22 06:33

import amang.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amang.group')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
            bases=('amang.group',),
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='amang.group')),
                ('number', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Generation')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main')),
            ],
            options={
                'verbose_name': 'Generation',
                'verbose_name_plural': 'Generations',
            },
            bases=('amang.group',),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amang.group')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
            bases=('amang.group',),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start Time')),
                ('end', models.DateTimeField(verbose_name='End Time')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amang.member', verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amang.member', verbose_name='Reader'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localtime, verbose_name='Date')),
                ('value', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('LATENESS', 'Lateness'), ('ABSENCE', 'Absence')], default=amang.models.AttendanceStatus['ATTENDANCE'], max_length=20, verbose_name='Attendance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amang.member')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='MemberSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='Priority')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amang.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amang.session')),
            ],
            options={
                'verbose_name': '부원 Session',
                'verbose_name_plural': '부원 세션',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amang.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='member',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amang.generation', verbose_name='Generation'),
        ),
        migrations.AddField(
            model_name='member',
            name='sessions',
            field=models.ManyToManyField(through='amang.MemberSession', to='amang.Session', verbose_name='Sessions'),
        ),
        migrations.AddField(
            model_name='generation',
            name='chairperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_generation', to='amang.member', verbose_name='Chairperson'),
        ),
        migrations.AddField(
            model_name='generation',
            name='vice_chairperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_read_generation', to='amang.member', verbose_name='Vice-Chairperson'),
        ),
    ]
