# Generated by Django 3.1.1 on 2020-09-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.CharField(max_length=100, verbose_name='Meeting Link')),
            ],
        ),
    ]
