# Generated by Django 3.1.1 on 2020-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amang', '0002_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='Activate'),
        ),
    ]
