# Generated by Django 3.1.1 on 2020-10-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amang', '0003_member_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='activate',
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
