# Generated by Django 5.0.7 on 2024-07-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amang', '0004_auto_20201007_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersession',
            options={'verbose_name': 'Member Session', 'verbose_name_plural': 'Member 세션'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='director',
            field=models.CharField(max_length=20, verbose_name='Director'),
        ),
    ]
